# Generated by Django 4.2 on 2023-04-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="exercise",
            name="base",
            field=models.ManyToManyField(to="moves.base"),
        ),
    ]
