# Generated by Django 4.2 on 2023-04-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0002_base_exercise_base"),
    ]

    operations = [
        migrations.RemoveField(model_name="exercise", name="muscle_groups",),
        migrations.AddField(
            model_name="exercise",
            name="importance",
            field=models.CharField(
                choices=[
                    ("important", "Important"),
                    ("variation", "Variation"),
                    ("interesting", "Interesting"),
                    ("whanky", "whanky"),
                ],
                default="important",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(model_name="exercise", name="base",),
        migrations.AlterField(
            model_name="exercise",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                max_length=100,
            ),
        ),
        migrations.DeleteModel(name="Base",),
        migrations.DeleteModel(name="MuscleGroup",),
        migrations.AddField(
            model_name="exercise",
            name="base",
            field=models.CharField(
                choices=[("lbase", "L-Base"), ("standing", "Standing")],
                default="important",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
