# Generated by Django 4.2 on 2023-04-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0004_exercise_dance_exercise_flow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="pops",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exercise",
            name="whips",
            field=models.BooleanField(default=False),
        ),
    ]
