# Generated by Django 4.2 on 2023-04-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0005_exercise_pops_exercise_whips"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise", old_name="flow", new_name="flows",
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="washing_machine",
            new_name="washing_machines",
        ),
    ]
