# Generated by Django 4.2 on 2023-04-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0006_rename_flow_exercise_flows_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="legit",
            field=models.BooleanField(default=False),
        ),
    ]
