# Generated by Django 4.2 on 2023-04-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0007_exercise_legit"),
    ]

    operations = [
        migrations.RemoveField(model_name="exercise", name="importance",),
        migrations.AddField(
            model_name="exercise",
            name="counterbalance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exercise",
            name="position",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exercise",
            name="type",
            field=models.CharField(
                choices=[
                    ("essential", "Essential"),
                    ("not_essential", "not_essential"),
                ],
                default="Essential",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exercise",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("expert", "Expert"),
                ],
                max_length=100,
            ),
        ),
    ]
