# Generated by Django 4.2 on 2023-04-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0008_remove_exercise_importance_exercise_counterbalance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="variation",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"position": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variations",
                to="moves.exercise",
            ),
        ),
    ]
