# Generated by Django 4.2 on 2023-04-20 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0009_exercise_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="type",
            field=models.CharField(
                choices=[
                    ("essential", "Essential"),
                    ("not_essential", "Not Essential"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Transition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_position",
                    models.ForeignKey(
                        limit_choices_to={"position": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_transitions",
                        to="moves.exercise",
                    ),
                ),
                (
                    "to_position",
                    models.ForeignKey(
                        limit_choices_to={"position": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_transitions",
                        to="moves.exercise",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exercise",
            name="entrance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exercise_entrances",
                to="moves.transition",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="exit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exercise_exits",
                to="moves.transition",
            ),
        ),
    ]
