# Generated by Django 4.2 on 2023-04-20 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0010_alter_exercise_type_transition_exercise_entrance_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="exercise", name="entrance",),
        migrations.RemoveField(model_name="exercise", name="exit",),
        migrations.AddField(
            model_name="exercise",
            name="entrance_from",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"position": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entrance_from_exercises",
                to="moves.exercise",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="entrance_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"position": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entrance_to_exercises",
                to="moves.exercise",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="exit_from",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"position": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exit_from_exercises",
                to="moves.exercise",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="exit_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"position": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exit_to_exercises",
                to="moves.exercise",
            ),
        ),
        migrations.DeleteModel(name="Transition",),
    ]
