# Generated by Django 4.2 on 2023-04-20 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0011_remove_exercise_entrance_remove_exercise_exit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="transition_from",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"position": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transition_from_exercises",
                to="moves.exercise",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="transition_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"position": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transition_to_exercises",
                to="moves.exercise",
            ),
        ),
    ]
