# Generated by Django 4.2 on 2023-04-20 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0013_alter_exercise_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="variation",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"position": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variations",
                to="moves.exercise",
            ),
        ),
    ]
