# Generated by Django 4.2 on 2023-04-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0014_alter_exercise_variation"),
        ("authuser", "0002_user_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="learned",
            field=models.ManyToManyField(
                blank=True, related_name="learned_by", to="moves.exercise"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="want_to_learn",
            field=models.ManyToManyField(
                blank=True, related_name="want_to_learn_by", to="moves.exercise"
            ),
        ),
    ]
