# Generated by Django 4.2 on 2023-04-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0014_alter_exercise_variation"),
        ("authuser", "0003_user_learned_user_want_to_learn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorited", to="moves.exercise"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="learned",
            field=models.ManyToManyField(
                blank=True, related_name="learned", to="moves.exercise"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="want_to_learn",
            field=models.ManyToManyField(
                blank=True, related_name="want_to_learn", to="moves.exercise"
            ),
        ),
    ]
