# Generated by Django 4.2 on 2023-04-07 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_unit_date_training"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="Date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="unit",
            name="userThatTrains",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.training",
            ),
        ),
    ]
