# Generated by Django 4.2 on 2023-04-07 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0008_alter_training_usertraining"),
    ]

    operations = [
        migrations.RemoveField(model_name="set", name="Set",),
        migrations.AddField(
            model_name="set",
            name="Excercise",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.excercise",
            ),
        ),
        migrations.AddField(
            model_name="set",
            name="userSet",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.training",
            ),
        ),
        migrations.AlterField(
            model_name="excercise",
            name="author",
            field=models.ForeignKey(
                default="authuser.User",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="Unit",),
    ]
