# Generated by Django 4.2 on 2023-04-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_remove_set_set_set_excercise_set_userset_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="set", old_name="userSet", new_name="Training",
        ),
    ]
